version: 1
formatters:
  customFormatter:
    format: '%(asctime)s %(levelname)s - %(filename)s#%(funcName)s:%(lineno)d: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

loggers:
  console:
    handlers: [consoleHandler]
    level: DEBUG
    qualname: console
    propagate: no
  file:
      handlers: [fileHandler]
      level: DEBUG
      qualname: app
      propagate: no
      suffix: '%Y-%m-%d'

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: customFormatter
    stream: ext://sys.stdout
  fileHandler:
    formatter: customFormatter
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    filename: logs/colf_simulator_core.log
    encoding: UTF-8 
    when: 'd'
    interval: 1   
    backupCount: 180 
    delay: True
root:
  level: DEBUG
  handlers: [consoleHandler, fileHandler]
